    ds_list_add(global.context_menu,"Make charred-tip arrows")
    global.context_menu_makeCharredTipArrowsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"Make charred-tip bolts")
    global.context_menu_makeCharredTipBoltsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have no bladed weapon and no sticks")
    global.context_menu_noBladeNoSticksID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have a bladed weapon but no sticks")
    global.context_menu_yesBladeNoSticksID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have a stick but no bladed weapon")
    global.context_menu_noBladeYesSticksID = (ds_list_size(global.context_menu) - 1)

    ds_list_add(global.context_menu,"Glue onto charred-tip arrows")
    global.context_menu_arrowheadsMakeArrowsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"Glue onto charred-tip bolts")
    global.context_menu_arrowheadsMakeBoltsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have no hide glue and no charred-tip arrows")
    global.context_menu_noGlueNoCharredtipArrowsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have hide glue but no charred-tip arrows")
    global.context_menu_yesGlueNoCharredtipArrowsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have charred-tip arrows but no hide glue")
    global.context_menu_noGlueYesCharredtipArrowsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have no hide glue and no charred-tip bolts")
    global.context_menu_noGlueNoCharredtipBoltsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have hide glue but no charred-tip bolts")
    global.context_menu_yesGlueNoCharredtipBoltsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have charred-tip bolts but no hide glue")
    global.context_menu_noGlueYesCharredtipBoltsID = (ds_list_size(global.context_menu) - 1)
