    ds_list_add(global.context_menu,"Make charred-tip arrows")
    global.context_menu_makeCharredTipArrowsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"Make charred-tip bolts")
    global.context_menu_makeCharredTipBoltsID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have no bladed weapon and no sticks")
    global.context_menu_noBladeNoSticksID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have a bladed weapon but no sticks")
    global.context_menu_yesBladeNoSticksID = (ds_list_size(global.context_menu) - 1)
    ds_list_add(global.context_menu,"You have a stick but no bladed weapon")
    global.context_menu_noBladeYesSticksID = (ds_list_size(global.context_menu) - 1)
